worker_processes auto;

events {
    worker_connections 768;
}

http {
    include mime.types;

    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers on;
    server_tokens off;


    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name tgroeppm.42.fr;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        root /var/www/html;
        access_log /var/log/nginx/yourdomain.com-access.log;
        error_log  /var/log/nginx/yourdomain.com-error.log error;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Adminer configuration
        location /adminer/ {
            fastcgi_index adminer.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/adminer.php;
            fastcgi_pass adminer:9000;
        }
    }
}