version: '3'

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception_network

  wordpress:
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - inception_network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgroepp/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/tgroepp/data/mysql
      o: bind

networks:
  inception_network:
    driver: bridge


# version: '3'

# services:
#   nginx:
#     build: 
#       context: ./requirements/nginx
#       dockerfile: Dockerfile
#     ports:
#       - "443:443"
#     volumes:
#       - wordpress_data:/var/www/html
#       - ./requirements/nginx/conf:/etc/nginx/conf.d
#     environment:
#       - DOMAIN_NAME=${DOMAIN_NAME}
#       - SSL_DAYS_VALID=365
#     depends_on:
#       - wordpress
#     restart: always
#     networks:
#       - inception_network

#   wordpress:
#     build: 
#       context: ./requirements/wordpress
#       dockerfile: Dockerfile
#     volumes:
#       - wordpress_data:/var/www/html
#     environment:
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#       - MYSQL_USER=${MYSQL_USER}
#       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#     depends_on:
#       - mariadb
#     restart: always
#     networks:
#       - inception_network

#   mariadb:
#     build:
#       context: ./requirements/mariadb
#       dockerfile: Dockerfile
#     volumes:
#       - db_data:/var/lib/mysql
#     environment:
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#       - MYSQL_USER=${MYSQL_USER}
#       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#     restart: always
#     networks:
#       - inception_network

# volumes:
#   wordpress_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/wordpress
#       o: bind
#   db_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/${USER}/data/mysql
#       o: bind

# networks:
#   inception_network:
#     driver: bridge